services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: proration-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile
    image: proration-client
    ports:
      - "3000:80"
